env:
  contexts:
    - name: notes-app-context
      urls:
        - "http://localhost"
      includePaths:
        - "http://localhost/.*"

      authentication:
        method: json
        parameters:
          loginPageUrl: "http://localhost"
          loginRequestUrl: "http://localhost/api/login"
          loginRequestBody: '{"username":"${ZAP_APP_USER}","password":"${ZAP_APP_PASSWORD}"}'
        verification:
          method: response
          loggedInRegex: "autenticación correcta"
          loggedOutRegex: "autenticación requerida"

      users:
        - name: zap-user
          credentials:
            username: "${ZAP_APP_USER}"
            password: "${ZAP_APP_PASSWORD}"

  parameters:
    failOnError: true
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: notes-app-context
      maxDuration: 2

  - type: spiderAjax
    parameters:
      context: notes-app-context
      maxDuration: 2

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      context: notes-app-context
      user: zap-user
      policy: Default Policy
      maxScanDurationInMins: 5

  - type: report
    parameters:
      template: modern
      reportDir: /zap/wrk/reports
      reportFile: zap-report-ci
      reportTitle: "Notes App - Security Scan Report"
