name: ZAP Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Levantar la App con Docker Compose
        env:
          APP_USER: ${{ secrets.APP_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          docker compose up -d
          sleep 30

      - name: ZAP Scan (Automation Framework)
        uses: zaproxy/action-af@v0.3.0
        env:
          ZAP_APP_USER: ${{ secrets.APP_USER }}
          ZAP_APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        with:
          plan: '.zap/zap-plan.yml'
          cmd_options: '--add-host=host.docker.internal:host-gateway'
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          docker_env_vars: |
            ZAP_APP_USER
            ZAP_APP_PASSWORD

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: reports/
          retention-days: 7
